;; This logfile was generated automatically by `xindy'
;; at 06.02.2022  02:08:37
;; Indexstyle: "C:\\THESIS\\Temp\\try out_2\\try out\\oG5PK6CqQY", Rawindex: "C:\\THESIS\\Temp\\try out_2\\try out\\drU1fmrTEm", Output: "document.acr"


Building indexentry-tree:
Hierdepth of index is :TREE

sort-indexentries: (FORWARD BACKWARD FORWARD FORWARD)

Forming letter-groups:
sort-indexentries: (FORWARD BACKWARD FORWARD FORWARD)
Letter-group: "È¨" -> "P"